# Generated by Django 5.2 on 2025-07-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardsummary",
            name="recommendations",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dependents",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="income",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="investments",
            field=models.TextField(blank=True, default=""),
        ),
    ]
