# Generated by Django 5.2 on 2025-07-28 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_dashboardsummary_recommendations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardsummary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboardsummary",
            name="monthly_savings",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="dashboardsummary",
            name="progress_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="dashboardsummary",
            name="savings_goal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_fund",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="investment_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="investment_types",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="monthly_savings",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="retirement_savings",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="savings_goal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tax_deductions",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_savings",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
