# Generated by Django 5.2.4 on 2025-07-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dashboardsummary_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="business_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="marital_status",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="property_owned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vehicle_owned",
            field=models.BooleanField(default=False),
        ),
    ]
