# Generated by Django 5.2.4 on 2025-08-08 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_business_type_userprofile_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                ("sub_genre", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("rating", models.FloatField(default=0.0)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("cover_image_url", models.URLField(blank=True)),
                ("amazon_url", models.URLField(blank=True)),
                ("investment_level", models.CharField(blank=True, max_length=50)),
                ("financial_topics", models.TextField(blank=True)),
                (
                    "difficulty_level",
                    models.CharField(default="Beginner", max_length=20),
                ),
                ("embedding_vector", models.TextField(blank=True)),
                ("popularity_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating", "-popularity_score"],
            },
        ),
        migrations.CreateModel(
            name="UserReadingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_genres", models.JSONField(default=list)),
                ("preferred_authors", models.JSONField(default=list)),
                ("preferred_topics", models.JSONField(default=list)),
                (
                    "preferred_difficulty",
                    models.CharField(default="Beginner", max_length=20),
                ),
                (
                    "preferred_investment_level",
                    models.CharField(default="Beginner", max_length=20),
                ),
                ("books_per_month", models.IntegerField(default=1)),
                ("reading_goal", models.IntegerField(default=12)),
                ("user_embedding", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_score", models.FloatField()),
                ("recommendation_reason", models.TextField()),
                ("recommendation_type", models.CharField(max_length=50)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_clicked", models.BooleanField(default=False)),
                ("is_added_to_list", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recommendation_score"],
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="UserReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_read", "Want to Read"),
                            ("currently_reading", "Currently Reading"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="want_to_read",
                        max_length=20,
                    ),
                ),
                ("user_rating", models.FloatField(blank=True, null=True)),
                ("user_review", models.TextField(blank=True)),
                ("pages_read", models.IntegerField(default=0)),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("time_spent_reading", models.IntegerField(default=0)),
                ("last_read_date", models.DateTimeField(blank=True, null=True)),
                ("interaction_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
